repos:
  # Basic hygiene checks. These are fast and catch common mistakes early.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key

  # Ruff = linter + quick, safe autofixes. Run this before formatters.
  # We purposely DO NOT use ruff-format because Black will be our formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]  # apply safe autofixes; leave style to Black

  # Sort imports in a way compatible with Black.
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Black = single source of truth for formatting. Run after ruff + isort.
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "88"]

  # Type checking last; it’s slower and benefits from earlier fixes.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--python-version=3.10"]
        additional_dependencies:
          - fastapi>=0.111
          - pydantic>=2.7
          - pydantic-settings>=2.2
          - uvicorn[standard]>=0.30
          - asyncpg>=0.29
          - httpx>=0.27
          - pytest>=7.0
